name: Sync Images via Skopeo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "images.yaml"
      - "auths.yaml"
      - ".github/workflows/actions.yaml"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y skopeo

      - name: Generate and Execute Login Commands
        uses: mikefarah/yq@v4
        with:
          cmd: |
            yq e '.auths | to_entries[] | 
                  "docker login \(.key) -u \(.username) -p \(.password)"' auths.yaml | sh

      - name: Sync Images (Generate & Execute)
        uses: mikefarah/yq@v4
        with:
          cmd: |
            yq e '.images[] | 
                  "skopeo copy --all docker://\(.source) docker://\(.target)"' images.yaml | sh
