name: Sync Images via Skopeo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "images.yaml"
      - "auths.yaml"
      - ".github/workflows/actions.yaml"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y skopeo wget
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Sync
        run: |
          bash sync.sh
