name: Sync Images via Skopeo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "images.yaml"
      - "auths.yaml"
      - ".github/workflows/actions.yaml"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y skopeo yq

      - name: Generate and Execute Login Commands
        run: |
          bash sync.sh
