name: Sync Images via Skopeo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "images.yaml"
      - "auths.yaml"
      - "sync.sh"
      - "*.txt"
      - ".github/workflows/actions.yaml"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y skopeo wget
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Sync
        env:
          # 在这里列出所有需要的 Secrets
          ALIYUN_USER: ${{ secrets.ALIYUN_USER }}
          ALIYUN_PASS: ${{ secrets.ALIYUN_PASS }}
        run: |
          bash sync.sh
        continue-on-error: false
